#!/bin/bash

DB_DIR='./db'

function usage() {
	echo -e "This tools prints usage and examples for aws cli commands"
	echo -e "awscli-helper <s3> commands - To list commands supported by a service" 
	echo -e "awscli-helper <s3> <ls> <action> - Where action is description|usage|examples. Empty action prints everything"
	exit 1
}

if [[ $1 == "help" ]]; then
	usage
fi

SYNOPSIS_EXTN='syn'
DESCRIPTION_EXTN='desc'
EXAMPLES_EXTN='examples'

SERVICE=$1
COMMAND=$2
ACTION=$3

function validate() {
	if [[ $# == 0 ]]; then
		echo "print usage"
		usage
	fi

	if [[ $SERVICE != "" && $COMMAND == "" ]]; then
		usage
	fi
}

validate $@

echo -e "\n"
if [[ $COMMAND == "commands" ]]; then
	cat $DB_DIR/$SERVICE/commands	
elif [[ $ACTION == "description" || $ACTION == "desc" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.$DESCRIPTION_EXTN
elif [[ $ACTION == "usage" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.$SYNOPSIS_EXTN
elif [[ $ACTION == "examples" && -e $DB_DIR/$SERVICE/$COMMAND.$EXAMPLES_EXTN ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.$EXAMPLES_EXTN
elif [[ $ACTION == "" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.$DESCRIPTION_EXTN
	echo -e "\n*****\n"
	cat $DB_DIR/$SERVICE/$COMMAND.$SYNOPSIS_EXTN
	echo -e "\n*****\n"
	cat $DB_DIR/$SERVICE/$COMMAND.$EXAMPLES_EXTN
fi

echo -e "\n"
echo -e "Service Reference: https://docs.aws.amazon.com/cli/latest/reference/$SERVICE/index.html"
if [[ $COMMAND != "" && $COMMAND != "commands" ]]; then
	echo -e "Command Reference: https://docs.aws.amazon.com/cli/latest/reference/$SERVICE/$COMMAND.html"
fi
echo -e "\n"
