#!/bin/bash

DB_DIR='./db'

function usage() {
	echo -e "This tools prints usage and examples for aws cli commands"
	echo -e "awscli-helper <s3> commands - To list commands supported by a service" 
	echo -e "awscli-helper <s3> <ls> <action> - Where action is description|usage|examples. Empty action prints everything"
	exit 1
}

SERVICE=$1
COMMAND=$2
ACTION=$3

function validate() {
	if [[ $# == 0 ]]; then
		echo "print usage"
		usage
	fi

	if [[ $SERVICE != "" && $COMMAND == "" ]]; then
		usage
	fi
}

validate $@


if [[ $COMMAND == "commands" ]]; then
	cat $DB_DIR/$SERVICE/commands
elif [[ $ACTION == "description" || $ACTION == "desc" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.des
elif [[ $ACTION == "usage" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.syn
elif [[ $ACTION == "examples" ]]; then
	cat $DB_DIR/$SERVICE/$COMMAND.exmpl
else
	cat $DB_DIR/$SERVICE/$COMMAND.des
	echo -e "\n*****\n"
	cat $DB_DIR/$SERVICE/$COMMAND.syn
	echo -e "\n*****\n"
	cat $DB_DIR/$SERVICE/$COMMAND.exmpl	
fi